version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase # Example URL, adjust as needed
      # Add any other necessary environment variables here
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: athip
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ai_agent
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose DB port to host (optional, for debugging)
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge